"""empty message

Revision ID: 25f4f234760c
Revises: bc7ce380145f
Create Date: 2017-04-29 13:31:11.948314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25f4f234760c'
down_revision = 'bc7ce380145f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graphs', sa.Column('user_name', sa.String(), nullable=True))
    op.drop_constraint('graphs_user_id_fkey', 'graphs', type_='foreignkey')
    op.create_foreign_key(None, 'graphs', 'users', ['user_name'], ['username'])
    op.drop_column('graphs', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graphs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'graphs', type_='foreignkey')
    op.create_foreign_key('graphs_user_id_fkey', 'graphs', 'users', ['user_id'], ['id'])
    op.drop_column('graphs', 'user_name')
    # ### end Alembic commands ###
