"""empty message

Revision ID: 6a9c9ba9c200
Revises: a048db1a5ead
Create Date: 2017-05-14 21:40:28.866081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a9c9ba9c200'
down_revision = 'a048db1a5ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('graphs_user_name_fkey', 'graphs', type_='foreignkey')
    op.drop_column('graphs', 'created_at')
    op.drop_column('graphs', 'short_url')
    op.drop_column('graphs', 'user_name')
    op.add_column('meta', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('meta', sa.Column('short_url', sa.String(), nullable=True))
    op.add_column('meta', sa.Column('user_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'meta', 'users', ['user_name'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meta', type_='foreignkey')
    op.drop_column('meta', 'user_name')
    op.drop_column('meta', 'short_url')
    op.drop_column('meta', 'created_at')
    op.add_column('graphs', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('graphs', sa.Column('short_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('graphs', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key('graphs_user_name_fkey', 'graphs', 'users', ['user_name'], ['username'])
    # ### end Alembic commands ###
