"""empty message

Revision ID: a048db1a5ead
Revises: 75f579d01f0d
Create Date: 2017-05-13 19:24:59.969661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a048db1a5ead'
down_revision = '75f579d01f0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('graph_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['graph_id'], ['graphs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('graphs', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graphs', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('meta')
    # ### end Alembic commands ###
