"""Store graphs in serialized_settings as json

Revision ID: ad1e4d5e54cb
Revises: 489dffd78cd9
Create Date: 2017-06-01 16:14:26.994142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad1e4d5e54cb'
down_revision = '489dffd78cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graphs', sa.Column('serialized_graph', sa.String(), nullable=True))
    op.drop_column('graphs', 'serialized_string')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graphs', sa.Column('serialized_string', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('graphs', 'serialized_graph')
    # ### end Alembic commands ###
