"""empty message

Revision ID: bc7ce380145f
Revises: 1a25df04c6a2
Create Date: 2017-04-26 15:42:25.599045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc7ce380145f'
down_revision = '1a25df04c6a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graphs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'graphs', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'name')
    op.drop_constraint(None, 'graphs', type_='foreignkey')
    op.drop_column('graphs', 'user_id')
    # ### end Alembic commands ###
